### ISSUE TITLE
[Error] pelican-data-files: DATA_FILES_DIR path doesn't exists.

### ISSUE THREAD

**Issue by apowell656** [LucasVanHaaren/pelican-data-files#11] opened 2021-12-24 12:48 UTC
Followed all instructions that you have laid out. I am using Pelican 4.7.1 and the error persists. I even created a fresh virtual environment just in case with the same result.

**Comment by LucasVanHaaren** [comment] 2021-12-25 11:39
Hello, 

Can you please describe more how to reproduce the bug ?
This error said the data files directory (`data/` by default) is not existing !

Do you have created a `data` directory at your project's root ?

**Comment by apowell656** [comment] 2021-12-27 21:18
Hello,
I have the folder in the project root:

Pelican 4.7.1
Python 3.9.9

![Screen Shot 2021-12-27 at 3 51 16 PM](https://user-images.githubusercontent.com/1969515/147506429-9a563815-7d94-40b1-a6a0-63d84d49d4f7.png)

I have installed the plugin with `pip install pelican-data-files`.

```
[16:10:22] INFO     Plugins found:                                                                _utils.py:38
                    pelican.plugins.data_files                                                                
                    pelican.plugins.yaml_metadata   
```

Here is the sample JSON file I am using named `navigation.json`:

``` 
{
    "main": {
        "about": {
            "url": "/about/",
            "name": "About"
        }
    },
    "footer": {
        "home": {
            "url": "/",
            "name": "Home"
        },
        "about": {
            "url": "/about/",
            "name": "About"
        }
    }
}
```
 In my template I am using:

```
{% for item in DATA_NAVIGATION["main"] %}
    {{ item.name }}
{% endfor %}
```
When generating the site this is the output:
```
 pelican -l -r
  --- AutoReload Mode: Monitoring `content`, `theme` and `settings` for changes. ---
Serving site at: http://127.0.0.1:8000 - Tap CTRL-C to stop

-> Modified: settings, content, theme, images. re-generating...
pelican-data-files: DATA_FILES_DIR path doesn't exists.
``` 
Of course, the site will not regenerate with this error and if I explicitly call the plugin the error is the same.

I hope this is more clear.

**Comment by LucasVanHaaren** [comment] 2022-01-07 22:35
Hello @apowell656, sorry for the delay I was pretty busy !

This appears to be an issue with the auto-reload feature (`-r`) 
I will investigate the problem in the next few days

Just to know, are you looking to use it to create a theme or a website ?

**Comment by apowell656** [comment] 2022-01-08 20:01
@LucasVanHaaren  thanks for getting back to me and I understand. I am trying to add it to a site I have created and later on adding to a few themes.

**Comment by apowell656** [comment] 2022-02-02 18:30
@LucasVanHaaren quick question this should work as long as I am not using auto-reload (-r)? So an option would to be use 'make regenerate'? I will give that a shot when I get back to my office.

**Comment by LucasVanHaaren** [comment] 2022-02-02 22:04
Yes, without auto-reload it should work.

I will soon find out about the management of pelican hooks for plugins, in order to make the auto-reload feature work for this plugin (if possible).

**Comment by apowell656** [comment] 2022-02-11 18:07
Thanks for the update.

**Comment by LucasVanHaaren** [comment] 2022-07-25 07:18
Hi @apowell656,

After some research, I just found that this problem is not related to the use of the auto-reloading feature but to a breaking change introduced in pelican since version 4.5.1.

I haven’t identified the change yet and so I’ve released a fix that downgrade the pelican version to 4.5.1 which fixes this problem.

You can use the plugin by upgrading all dependencies via pip

On the other hand, the auto-reloading feature still doesn’t work for now, I will investigate deeper.

**Comment by apowell656** [comment] 2022-08-03 14:48
@LucasVanHaaren I will give it another shot in the next few days and let you know if I can get it to work. Thanks for the update.

**Comment by S1SYPHOS** [comment] 2022-09-23 14:27
I investigated this, and as it happens, `pelican` expects your `data` directory to be inside `content` - moving it there makes all your troubles go away :smiling_face_with_tear:

As far as I can see, this applies from v4.5.0 all the way to v4.8.0

**Comment by LucasVanHaaren** [comment] 2022-10-03 18:15
Hey @apowell656, 
as @S1SYPHOS said it was just an expected path issue ...

New release (v1.2.0) will fix this, you can simply upgrade the package with pip to test it out !

Feel free to come back to me and reopen this issue if this problem persists for you :smiley:

**Closed as completed by LucasVanHaaren** 2022-10-03 18:15 UTC
Labels: bug
